// Demo-data generator: creates random patients with mixed-format reports
// (text PDFs, PNG scans, JPEGs), uploads them through the REAL public
// booking API, allocates them as the doctor, and verifies the whole
// pipeline end to end:
//   - attachments land in data/uploads (server-random names),
//   - text PDFs are chunked + embedded into the RAG index at booking time,
//   - image uploads are stored but deliberately NOT indexed (no OCR),
//   - a .docx upload is rejected by the MIME whitelist,
//   - allocation promotes attachments to the patient and re-parents the
//     RAG chunks inside the approval transaction.
//
// Prereqs: backend running on :4000, seeded DB, embedding model cached in
// data/models (first run downloads ~23 MB once).
// Run: node scripts/demo-uploads.mjs
import fs from "fs";
import path from "path";
import crypto from "crypto";
import PDFDocument from "pdfkit";
import sharp from "sharp";
import Database from "better-sqlite3";

const BASE = process.argv[2] || "http://127.0.0.1:4000";
const ROOT = process.cwd();
const OUT_DIR = path.join(ROOT, "data", "demo-reports");
const DB_PATH = path.join(ROOT, "data", "pulseid.db");

const DOCTOR_LOGIN = { email: "ayesha.raza@pulseid.dev", password: "doctor123" };

let passed = 0;
let failed = 0;
function ok(cond, label, extra = "") {
  if (cond) {
    passed++;
    console.log(`  PASS  ${label}`);
  } else {
    failed++;
    console.error(`  FAIL  ${label}${extra ? ` — ${extra}` : ""}`);
  }
}

let ip = 40;
const nextIp = () => `10.90.0.${++ip}`;

// ---------------------------------------------------------------------------
// File generators
// ---------------------------------------------------------------------------

function generateTextPdf(filePath, title, patientName, sections) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 56 });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);
    doc.fontSize(16).font("Helvetica-Bold").fillColor("#111").text(title);
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor("#444").text(`Patient: ${patientName}`);
    doc.text(`Generated: ${new Date().toISOString().slice(0, 10)}`);
    doc.moveDown(0.8);
    for (const [heading, body] of sections) {
      doc.fontSize(11).font("Helvetica-Bold").fillColor("#0E7C7B").text(heading);
      doc.moveDown(0.2);
      doc.fontSize(10).font("Helvetica").fillColor("#222").text(body, { lineGap: 2 });
      doc.moveDown(0.6);
    }
    doc.fontSize(8).fillColor("#888").text("Demo document generated by scripts/demo-uploads.mjs — synthetic data only.");
    doc.end();
    stream.on("finish", resolve);
    stream.on("error", reject);
  });
}

async function generateScanImage(filePath, title, patientName, format /* png | jpeg */) {
  const width = 620;
  const height = 860;
  const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;");
  const rows = [
    { size: 22, weight: "bold", text: title, y: 60 },
    { size: 13, weight: "normal", text: `Patient: ${esc(patientName)}`, y: 110 },
    { size: 13, weight: "normal", text: `Date: ${new Date().toISOString().slice(0, 10)}`, y: 134 },
    { size: 13, weight: "normal", text: "Ref: DEMO-SCAN-" + crypto.randomInt(100000, 999999), y: 158 },
    { size: 12, weight: "normal", text: "— Image reports are stored verbatim in PulseID —", y: 800 },
    { size: 12, weight: "normal", text: "   they are viewable/downloadable, not text-indexed (no OCR).", y: 822 },
  ];
  const svg = `<svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
    <rect width="100%" height="100%" fill="#fdfcf7"/>
    <rect x="24" y="24" width="${width - 48}" height="${height - 48}" fill="none" stroke="#9aa5a4" stroke-width="2"/>
    ${rows.map((r) => `<text x="48" y="${r.y}" font-family="DejaVu Sans, sans-serif" font-size="${r.size}" font-weight="${r.weight}" fill="#1c2b2a">${r.text}</text>`).join("\n")}
  </svg>`;
  const pipeline = sharp({ create: { width, height, channels: 3, background: "#fdfcf7" } }).composite([
    { input: Buffer.from(svg), top: 0, left: 0 },
  ]);
  if (format === "jpeg") await pipeline.jpeg({ quality: 82 }).toFile(filePath);
  else await pipeline.png().toFile(filePath);
}

// ---------------------------------------------------------------------------
// Random patients + their report sets (3-4 files each, mixed formats)
// ---------------------------------------------------------------------------

const PATIENTS = [
  {
    fullName: "Ayesha Khan",
    nationalId: "43101-5550123-8",
    dateOfBirth: "1994-03-12",
    gender: "female",
    phoneNumber: "0300-5012345",
    reason: "Recurrent migraines, need neurology review",
    files: ["lab-panel.pdf", "mri-summary.pdf", "scan-prescription.png", "ultrasound.jpg"],
  },
  {
    fullName: "Faisal Mehmood",
    nationalId: "43202-6610234-4",
    dateOfBirth: "1987-11-02",
    gender: "male",
    phoneNumber: "0301-6023456",
    reason: "Follow-up for thyroid function tests",
    files: ["blood-report.pdf", "endocrine-clinic.pdf", "vaccine-card.png"],
  },
  {
    fullName: "Sana Riaz",
    nationalId: "43303-7720345-9",
    dateOfBirth: "2001-06-25",
    gender: "female",
    phoneNumber: "0302-7034567",
    reason: "Persistent anemia despite supplements",
    files: ["cbc-report.pdf", "ecg-summary.pdf", "referral-letter.pdf", "discharge.jpg"],
  },
];

const PDF_CONTENT = {
  "lab-panel.pdf": (n) => [
    ["History of Present Illness", `${n} presents with recurrent throbbing headaches, 3-4 episodes per month for the last six months, each lasting 6-12 hours with photophobia and nausea. No visual aura reported.`],
    ["Investigation Results", "CBC: Hb 12.9 g/dL, WBC 7.2, Platelets 265k. Serum TSH 2.1 mIU/L (normal). Vitamin D 18 ng/mL (deficient). Serum ferritin 22 ng/mL (low-normal)."],
    ["Impression", "Migraine without aura with concurrent vitamin D deficiency. No secondary-cause red flags on screening bloodwork."],
  ],
  "mri-summary.pdf": (n) => [
    ["Indication", `Rule out intracranial pathology in ${n} due to change in headache pattern.`],
    ["Findings", "MRI brain with contrast: no mass lesion, no demyelination, no acute infarct. Mild nonspecific white-matter changes, unchanged from prior study. Paranasal sinuses clear."],
    ["Conclusion", "Unremarkable MRI brain. Clinical correlation advised; continue symptomatic management."],
  ],
  "blood-report.pdf": (n) => [
    ["Specimen", `Fasting venous sample from ${n}, collected 08:10.`],
    ["Results", "TSH 6.8 mIU/L (high), Free T4 0.7 ng/dL (low), Anti-TPO 340 IU/mL (positive). Fasting glucose 5.1 mmol/L. Lipid panel within limits."],
    ["Interpretation", "Pattern consistent with autoimmune (Hashimoto) hypothyroidism. Recommend endocrine review and levothyroxine initiation per weight."],
  ],
  "endocrine-clinic.pdf": (n) => [
    ["History of Present Illness", `${n} reports fatigue, cold intolerance and 6 kg weight gain over four months. Family history of thyroid disease in the mother.`],
    ["Examination Findings", "BMI 28.4. Pulse 58 bpm regular. Dry skin noted. No goitre, no tremor, deep tendon reflexes with delayed relaxation."],
    ["Plan", "Start levothyroxine 50 mcg daily, recheck TSH in 6 weeks. Dietary counselling given."],
  ],
  "cbc-report.pdf": (n) => [
    ["Indication", `Microcytic anemia workup for ${n}: Hb 9.8 g/dL, MCV 71 fL.`],
    ["Results", "Ferritin 6 ng/mL (low). Transferrin saturation 9%. Stool occult blood negative x3. Coeliac serology negative."],
    ["Impression", "Iron-deficiency anemia, most likely dietary/increased losses. No malabsorption screen positive."],
  ],
  "ecg-summary.pdf": (n) => [
    ["Indication", `Pre-referral ECG for ${n} before starting iron infusion therapy.`],
    ["Findings", "Sinus rhythm 78 bpm. Normal axis. No ischaemic changes. QTc 430 ms."],
    ["Conclusion", "Normal ECG. No cardiac contraindication to infusion therapy."],
  ],
  "referral-letter.pdf": (n) => [
    ["Referral", `This letter refers ${n} to the haematology clinic for evaluation of refractory iron-deficiency anemia despite 4 months of oral iron.`],
    ["Request", "Consider IV iron sucrose course and further evaluation of occult losses."],
  ],
};

const IMAGE_TITLES = {
  "scan-prescription.png": "Prescription Scan",
  "ultrasound.jpg": "Ultrasound Report",
  "vaccine-card.png": "Vaccination Card",
  "discharge.jpg": "Discharge Summary Scan",
};

// ---------------------------------------------------------------------------
// API helpers
// ---------------------------------------------------------------------------

function jar() {
  const map = new Map();
  return {
    capture(res) {
      for (const c of res.headers.getSetCookie()) {
        const [pair] = c.split(";");
        const eq = pair.indexOf("=");
        if (eq > 0) map.set(pair.slice(0, eq).trim(), pair.slice(eq + 1).trim());
      }
    },
    header() {
      return [...map.entries()].map(([k, v]) => `${k}=${v}`).join("; ");
    },
    csrf() {
      return map.get("pulseid_csrf") || "";
    },
  };
}

async function http(method, apiPath, { jar: cookieJar, body, form, ip: xff } = {}) {
  const headers = {};
  if (cookieJar?.header()) headers.cookie = cookieJar.header();
  headers["x-forwarded-for"] = xff || nextIp();
  if (form) {
    /* boundary set by fetch */
  } else if (body !== undefined) {
    headers["content-type"] = "application/json";
  }
  if (method !== "GET" && cookieJar?.csrf()) headers["x-csrf-token"] = cookieJar.csrf();
  const res = await fetch(`${BASE}${apiPath}`, {
    method,
    headers,
    body: form ?? (body !== undefined ? JSON.stringify(body) : undefined),
  });
  cookieJar?.capture(res);
  return { status: res.status, data: await res.json().catch(() => null) };
}

const db = new Database(DB_PATH, { readonly: false });
db.pragma("journal_mode = WAL");

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

async function waitForIndexing(registrationId, expectedMinimum, timeoutMs = 90_000) {
  const t0 = Date.now();
  while (Date.now() - t0 < timeoutMs) {
    const n = db
      .prepare("SELECT COUNT(*) AS n FROM rag_chunks WHERE registration_id = ?")
      .get(registrationId).n;
    if (n >= expectedMinimum) return n;
    await sleep(1500);
  }
  return db.prepare("SELECT COUNT(*) AS n FROM rag_chunks WHERE registration_id = ?").get(registrationId).n;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

fs.mkdirSync(OUT_DIR, { recursive: true });
console.log(`Generating mixed-format reports for ${PATIENTS.length} random patients…\n`);

for (const p of PATIENTS) {
  const slug = p.fullName.toLowerCase().replace(/\s+/g, "-");
  const dir = path.join(OUT_DIR, slug);
  fs.mkdirSync(dir, { recursive: true });
  p.files = p.files.map((f) => {
    const filePath = path.join(dir, f);
    if (f.endsWith(".pdf")) {
      const sections = (PDF_CONTENT[f] || (() => [["Summary", "Synthetic demo content."]]))(p.fullName);
      p.filesMeta ??= {};
      return { name: f, path: filePath, mime: "application/pdf", sections };
    }
    return { name: f, path: filePath, mime: f.endsWith(".png") ? "image/png" : "image/jpeg" };
  });

  for (const file of p.files) {
    if (file.mime === "application/pdf") {
      await generateTextPdf(file.path, file.name.replace(/\.pdf$/, "").replace(/-/g, " ").toUpperCase(), p.fullName, file.sections);
    } else {
      await generateScanImage(file.path, IMAGE_TITLES[file.name] || "Medical Report Scan", p.fullName, file.mime === "image/png" ? "png" : "jpeg");
    }
    ok(fs.existsSync(file.path) && fs.statSync(file.path).size > 200, `generated ${p.fullName}/${file.name} (${(fs.statSync(file.path).size / 1024).toFixed(1)} KB)`);
  }
}

// One .docx to prove the MIME whitelist rejects non-PDF/image documents.
console.log("\nUpload guard (.docx must be rejected):");
{
  const fd = new FormData();
  fd.append("nationalId", "43999-9999999-1");
  fd.append("fullName", "Docx Reject Test");
  fd.append("dateOfBirth", "1990-01-01");
  fd.append("gender", "male");
  fd.append("phoneNumber", "0300-0000001");
  const doctors = (await http("GET", "/api/booking/doctors")).data.doctors;
  fd.append("doctorId", doctors[0].id);
  fd.append("reports", new Blob([Buffer.from("PK\x03\x04 fake docx bytes")], { type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" }), "report.docx");
  const res = await http("POST", "/api/booking/requests", { form: fd });
  ok(res.status === 400 && /Only PDF, PNG, JPEG or WebP/i.test(res.data?.error || ""), "a .docx upload is refused by the MIME whitelist", JSON.stringify(res.data));
}

console.log("\nBooking the patients (through the real public API):");
for (const p of PATIENTS) {
  const fd = new FormData();
  for (const [k, v] of Object.entries({
    nationalId: p.nationalId,
    fullName: p.fullName,
    dateOfBirth: p.dateOfBirth,
    gender: p.gender,
    phoneNumber: p.phoneNumber,
    email: "",
    address: "",
    bloodGroup: "unknown",
    allergies: "",
    chronicConditions: "",
    weightKg: "",
    pediatricianName: "",
    pediatricianPhone: "",
    reason: p.reason,
  })) {
    fd.append(k, v);
  }
  const doctors = (await http("GET", "/api/booking/doctors", { ip: nextIp() })).data.doctors;
  fd.append("doctorId", doctors[0].id);
  for (const file of p.files) {
    fd.append("reports", new Blob([fs.readFileSync(file.path)], { type: file.mime }), file.name);
  }
  const res = await http("POST", "/api/booking/requests", { form: fd, ip: nextIp() });
  ok(res.status === 201, `${p.fullName}: booking accepted with ${res.data?.request?.attachments} attachments`);
  p.registrationId = res.data?.request?.id;
  if (!p.registrationId) {
    console.error("  !! booking failed:", JSON.stringify(res.data));
    continue;
  }
  // RAG indexing is async — wait for profile + at least one chunk per PDF.
  const pdfCount = p.files.filter((f) => f.mime === "application/pdf").length;
  const indexed = await waitForIndexing(p.registrationId, 1 + pdfCount);
  ok(indexed >= 1 + pdfCount, `${p.fullName}: RAG index ready (profile + ${pdfCount} PDFs) — ${indexed} chunks`, `only ${indexed}`);
}

console.log("\nAllocating each request as the doctor:");
const doctorJar = jar();
{
  const login = await http("POST", "/api/auth/doctor/login", { jar: doctorJar, body: DOCTOR_LOGIN });
  ok(login.status === 200, "doctor login");
  const list = (await http("GET", "/api/doctor/registrations", { jar: doctorJar })).data;
  for (const p of PATIENTS) {
    const row = list.registrations?.find((r) => r.nationalId === p.nationalId && r.status === "pending");
    ok(!!row, `${p.fullName}: pending request visible in the doctor's queue`);
    if (!row) continue;
    const alloc = await http("POST", `/api/doctor/registrations/${row.id}/allocate`, {
      jar: doctorJar,
      body: { scheduledAt: new Date(Date.now() + 864e5).toISOString() },
    });
    ok(alloc.status === 200 && alloc.data.patientId, `${p.fullName}: allocated — patient + appointment created`);
    p.patientId = alloc.data.patientId;
  }
}

console.log("\nVerifying stored files, RAG index, and approval promotion:");
for (const p of PATIENTS) {
  if (!p.patientId) continue;

  const attachments = db
    .prepare("SELECT id, stored_name, original_name, mime_type, patient_id FROM registration_attachments WHERE registration_id = ?")
    .all(p.registrationId);
  ok(attachments.length === p.files.length, `${p.fullName}: ${attachments.length} attachment rows on the registration`);

  const uploadsDir = path.join(ROOT, "data", "uploads");
  ok(attachments.every((a) => fs.existsSync(path.join(uploadsDir, a.stored_name))), `${p.fullName}: every uploaded file exists on disk (server-random names)`);

  ok(attachments.every((a) => a.patient_id === p.patientId), `${p.fullName}: attachments promoted to the patient at approval`);

  const chunks = db
    .prepare("SELECT source_type, source_id, label, length(embedding) AS emb FROM rag_chunks WHERE registration_id = ? OR patient_id = ?")
    .all(p.registrationId, p.patientId);
  const profile = chunks.filter((c) => c.source_type === "profile");
  const pdfChunks = chunks.filter((c) => c.source_type === "attachment");
  const visitChunks = chunks.filter((c) => c.source_type === "visit");
  ok(profile.length === 1 && profile[0].emb === 1536, `${p.fullName}: profile chunk embedded (1536-byte vector)`);
  ok(pdfChunks.length >= 1 && pdfChunks.every((c) => c.emb === 1536), `${p.fullName}: all PDF pages embedded (${pdfChunks.length} chunks)`);

  const imageAttachmentIds = attachments.filter((a) => a.mime_type !== "application/pdf").map((a) => a.id);
  ok(
    imageAttachmentIds.every((id) => !chunks.some((c) => c.source_id === id)),
    `${p.fullName}: image uploads stored but deliberately not indexed (${imageAttachmentIds.length} images)`
  );

  const visitRows = db.prepare("SELECT COUNT(*) AS n FROM medical_records WHERE patient_id = ?").get(p.patientId).n;
  ok(visitRows >= 1, `${p.fullName}: registration visit recorded (${visitRows})`);
  void visitChunks; // visits arrive later via the AI-report flow; none expected yet
}

console.log(`\n${passed} passed, ${failed} failed`);
db.close();
process.exit(failed > 0 ? 1 : 0);
